### PR TITLE
Issue #17

### PR DESCRIPTION
**Pull request by toleressea**

### CODE REVIEW

**Comment by bvarga** [comment]
Is this compiling in delphi, or just in FreePascal?

**Comment by toleressea** [comment]
That's my bad. I just pushed some corrections that aren't FPC specific, sorry!

**Comment by toleressea** [comment]
Ugh, actually I don't think that's any better. Standby...

**Comment by bvarga** [comment]
no worries :)

**Comment by toleressea** [comment]
What version of Delphi are you looking for compatibility in? From what I can tell, UInt64 (equivalent to FPC's QWord) wasn't available in Delphi 7, which unfortunately is my local Delphi environment. I could use an Int64 instead, which also works. Thoughts?

Edit: And I just answered my own question by reading the docs, Delphi 7+...

**Comment by toleressea** [comment]
Since it works in both FPC and Delphi, and it doesn't need to be unsigned to resolve the issue, I went with an `Int64`. I also limited the scope of my compilation fix to FPC only.

**Comment by toleressea** [comment]
@bvarga - Are you waiting on me?

**Comment by bvarga** [comment]
No, just forgot it, will merge it.

**Pull request merged**
